Summer/Informacijski sustavi/WebApp/Models/Mjesto.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class Mjesto
{
    public int IdMjesto { get; set; }

    public string Naziv { get; set; }

    public int Postanskibroj { get; set; }

    public virtual ICollection<Korisnik> Korisniks { get; set; } = new List<Korisnik>();

    public virtual ICollection<Putovanje> Putovanjes { get; set; } = new List<Putovanje>();
}

Summer/Informacijski sustavi/WebApp/ViewModels/MjestoViewModel.cs
namespace WebApp.ViewModels
{
    public class MjestoViewModel
    {

        public int idMjesto { get; set; }
        public string naziv { get; set; }
        public int postanskibroj { get; set; }
    }
}

Summer/Informacijski sustavi/WebApp/Controllers/MjestoController.cs
using WebApp.Models;
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using WebApp.ViewModels;
using System.Text.Json;
using System.Runtime.CompilerServices;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Azure;
using Microsoft.VisualBasic;
using WebApp.Extensions;


namespace WebApp.Controllers
{

    public class MjestoController : Controller
    {
        private readonly infsusContext ctx;
        private readonly ILogger<MjestoController> logger;

        public MjestoController(infsusContext ctx, ILogger<MjestoController> logger)
        {
            this.ctx = ctx;
            this.logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            Console.WriteLine("aha");

            var query = ctx.Mjesto.AsNoTracking();

            var mjesto = query.Select(o => new MjestoViewModel
            {
                idMjesto = o.IdMjesto,
                naziv = o.Naziv,
                postanskibroj = o.Postanskibroj

            });
            var model = new MjestaViewModel
            {
                mjesta = mjesto,
            };

            return View("Index", model);

        }


        public async Task<IActionResult> Search(string? naziv)
        {
            Console.WriteLine("aha");

            var query = ctx.Mjesto.AsNoTracking();

            if (naziv != null)
            {
                Console.WriteLine("usao sam u ovo");
                query = ctx.Mjesto.Where(p => p.Naziv.Equals(naziv));

                bool postoji = await ctx.Mjesto.AnyAsync(m => m.Naziv == naziv);

                if (!postoji)
                {
                    Console.WriteLine("nemam takav");
                    TempData[Constants.Message] = $"Ne postoji mjesto s tim imenom!!";
                    TempData[Constants.ErrorOccurred] = false;
                    return RedirectToAction(nameof(Index));
                }

                var mjesto = query.Select(o => new MjestoViewModel
                {
                    idMjesto = o.IdMjesto,
                    naziv = o.Naziv,
                    postanskibroj = o.Postanskibroj

                });
                var model = new MjestaViewModel
                {
                    mjesta = mjesto,
                };
                return View(model);
            }
            else
            {
                Console.WriteLine("nemam takav");
                TempData[Constants.Message] = $"Polje je prazno!!";
                TempData[Constants.ErrorOccurred] = false;
                return RedirectToAction(nameof(Index));
            }




        }



        //stvaranje nove vrste-GET
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //stvaranje nove vrste-POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Mjesto mjesto)
        {
            logger.LogTrace(JsonSerializer.Serialize(mjesto));
            if (ModelState.IsValid)
            {
                var postojeceMjesto1 = ctx.Mjesto.AsNoTracking().FirstOrDefault(m => m.Naziv.Equals(mjesto.Naziv));
                if (postojeceMjesto1 != null)
                {
                    ModelState.AddModelError("Naziv", "Naziv već postoji u bazi podataka.");
                    return View(); ;
                }
                var postojeceMjesto = ctx.Mjesto.AsNoTracking().FirstOrDefault(m => m.Postanskibroj == mjesto.Postanskibroj);
                if (postojeceMjesto != null)
                {
                    ModelState.AddModelError("Postanskibroj", "Poštanski broj već postoji u bazi podataka.");
                    return View(); ;
                }
                try
                {

                    ctx.Add(mjesto);
                    ctx.SaveChanges();
                    logger.LogInformation(new EventId(1000), $"Mjesto naziva {mjesto.Naziv} dodano!");

                    TempData[Constants.Message] = $"Mjesto naziva {mjesto.Naziv} dodano!";
                    TempData[Constants.ErrorOccurred] = false;
                    return RedirectToAction(nameof(Index));

                }

                catch (Exception exc)
                {
                    logger.LogError("Pogreška prilikom kreiranja mjesta");
                    ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
                    return View(mjesto);
                }
            }
            else
            {
                return View(mjesto);
            }
        }

        public IActionResult Delete(int idMjesta)
        {
            var brisanje = ctx.Mjesto.AsNoTracking()
                           .Where(Mjesto => Mjesto.IdMjesto == idMjesta).SingleOrDefault();
            if (brisanje != null)
            {
                try
                {
                    string naziv = brisanje.Naziv;
                    ctx.Remove(brisanje);
                    ctx.SaveChanges();
                    logger.LogInformation($"Mjesto naziva {naziv} uspješno obrisano");
                    TempData[Constants.Message] = $"Mjesto naziva {naziv} uspješno obrisano";
                    TempData[Constants.ErrorOccurred] = false;
                }
                catch (Exception exc)
                {
                    TempData[Constants.Message] = "Greška prilikom brisanja!";
                    TempData[Constants.ErrorOccurred] = true;
                    logger.LogError("Greška prilikom brisanja!");
                }
            }
            else
            {
                logger.LogWarning("Ne postoji mjesto s ID-jem {0}", idMjesta);
                TempData[Constants.Message] = "Ne postoji mjesto s ID-jem " + idMjesta;
                TempData[Constants.ErrorOccurred] = true;
            }
            return RedirectToAction(nameof(Index));
        }

        //azuriranje GET
        [HttpGet]
        public IActionResult Edit(int idMjesta)
        {
            var mjesto = ctx.Mjesto.AsNoTracking()
                            .Where(mjesto => mjesto.IdMjesto == idMjesta).SingleOrDefault();
            if (mjesto == null)
            {
                logger.LogWarning("Ne postoji mjesto");
                return NotFound("Ne postoji odabrano mjesto" + idMjesta);
            }
            else
            {
                return View(mjesto);
            }
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Update(int idMjesta)
        {
            try
            {
                Mjesto mjesto = await
                     ctx.Mjesto.Where(mjesta => mjesta.IdMjesto == idMjesta)
                     .FirstOrDefaultAsync();
                if (mjesto == null)
                {
                    return NotFound("Pogrešan id " + idMjesta);
                }

                if (await TryUpdateModelAsync<Mjesto>(mjesto, "",
                    vrsta => vrsta.IdMjesto, vrsta => vrsta.Naziv, vrsta => vrsta.Postanskibroj))
                {

                    bool nazivExists = await ctx.Mjesto
                      .AnyAsync(m => m.Naziv == mjesto.Naziv && m.IdMjesto != mjesto.IdMjesto);

                    if (nazivExists)
                    {
                        ModelState.AddModelError("Naziv", "Naziv već postoji u bazi podataka.");
                        TempData[Constants.Message] = $"Mjesto s nazivom {mjesto.Naziv} već postoji u bazi podataka.!";
                        TempData[Constants.ErrorOccurred] = true;
                        return View(mjesto);
                    }
                    bool exists = await ctx.Mjesto
                        .AnyAsync(m => m.Postanskibroj == mjesto.Postanskibroj && m.IdMjesto != mjesto.IdMjesto);

                    if (exists)
                    {
                        ModelState.AddModelError("Postanskibroj", "Poštanski broj već postoji u bazi podataka.");
                        return View(mjesto);
                    }

                  
                    try
                    {
                        await ctx.SaveChangesAsync();
                        TempData[Constants.Message] = $"Ažurirano mjesto naziva {mjesto.Naziv}!";
                        TempData[Constants.ErrorOccurred] = false;
                        return RedirectToAction(nameof(Index));

                    }
                    catch (Exception exc)
                    {
                        ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
                        return View(mjesto);
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Podaci se ne mogu povezati");
                    return View(mjesto);
                }

            }
            catch (Exception exc)
            {
                TempData[Constants.Message] = exc.CompleteExceptionMessage();
                TempData[Constants.ErrorOccurred] = true;
                return RedirectToAction(nameof(Edit), idMjesta);
            }
        }

    }
}

Summer/Informacijski sustavi/WebApp/Views/Mjesto/Create.cshtml
@model WebApp.Models.Mjesto
<style>
    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }

    img {
        border-radius: 10px;
    }

    div {
        margin-bottom: 10px;
    }

    a {
        color: green;
        text-decoration: none;
    }

    .alert-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 9999;
    }


    .fade-out {
        animation: fadeOut ease 2s;
        animation-fill-mode: forwards; 
    }

    @@keyframes fadeOut {
        0% { opacity: 1; }
        100% { opacity: 0; }
    }
</style>
<body>
    <h3>Unos novog mjesta</h3>
    

    <form asp-action="Create" method="post">

        <div class="form-group">
            Naziv mjesta:
            <input asp-for="Naziv" class="form-control" />
            <div><span asp-validation-for="Naziv" class="text-danger"></span></div>

            Poštanski broj:
            <input asp-for="Postanskibroj" class="form-control" />
            <div><span asp-validation-for="Postanskibroj" class="text-danger"></span></div>

        </div>

     
        <div class="alert-container">
            @if (TempData.ContainsKey(Constants.Message))
            {
                <div id="alert-message" class="alert alert-@((bool)TempData[Constants.ErrorOccurred] ? "danger" : "success")">
                    @TempData[Constants.Message]
                </div>
            }
        </div>

        <div class="text-center">
            <button class="btn btn-primary" type="submit">Dodaj</button>
            <a asp-action="Index" class="btn btn-secondary">Odustani</a>
        </div>


    </form>

     <script>

        var alertMessage = document.getElementById('alert-message');
        if (alertMessage) {
            setTimeout(function() {
                alertMessage.classList.add('fade-out');
            }, 3000); 
        }
    </script>


</body>
@section scripts {
    <partial name="IncludeValidation" />
}

Summer/Informacijski sustavi/WebApp/Views/Mjesto/Edit.cshtml
@model WebApp.Models.Mjesto
<style>
    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }

    img {
        border-radius: 10px;
    }

    div {
        margin-bottom: 10px;
    }

    a {
        color: green;
        text-decoration: none;
    }

    .alert-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 9999; 
    }

    .fade-out {
        animation: fadeOut ease 2s;
        animation-fill-mode: forwards; 
    }

    @@keyframes fadeOut {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0;
        }
    }
</style>

<h3>Ažuriranje mjesta</h3>
<form asp-route-idMjesta="@Model.IdMjesto" method="post">

    <div class="form-group">
        Naziv mjesta:
        <input asp-for="Naziv" class="form-control" />
        <div><span asp-validation-for="Naziv" class="text-danger"></span></div>


        Poštanski broj:
        <input asp-for="Postanskibroj" class="form-control" />
        <div><span asp-validation-for="Postanskibroj" class="text-danger"></span></div>

    </div>

    <div class="alert-container">
        @if (TempData.ContainsKey(Constants.Message))
        {
            <div id="alert-message" class="alert alert-@((bool)TempData[Constants.ErrorOccurred] ? "danger" : "success")">
                @TempData[Constants.Message]
            </div>
        }
    </div>
    <div class="text-center">
        <button class="btn btn-primary" type="submit">Spremi</button>
        <a asp-action="Index" class="btn btn-secondary">Odustani</a>
    </div>

</form>

<script>

    var alertMessage = document.getElementById('alert-message');
    if (alertMessage) {
        setTimeout(function () {
            alertMessage.classList.add('fade-out');
        }, 3000); 
    }
</script>

@section scripts {
    <partial name="IncludeValidation" />
}

Summer/Informacijski sustavi/WebApp/Views/Mjesto/Index.cshtml
@model WebApp.ViewModels.MjestaViewModel

@{
    ViewData["Title"] = "Mjesta";
}

<style>
    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }

    img {
        border-radius: 10px;
    }

    a {
        color: green;
        text-decoration: none;
    }

    .grid-container {
        display: grid;
        grid-template-columns: repeat(4, 1fr); /* 4 stupca */
        gap: 20px;
        padding: 20px;
    }

    .grid-item {
        background-color: rgba(255, 255, 255, 0.8);
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .alert-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 9999;
    }

    .fade-out {
        animation: fadeOut ease 2s;
        animation-fill-mode: forwards; 
    }

    @@keyframes fadeOut {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0;
        }
    }

</style>

<body>
  

    <h1>Mjesta</h1>
    <div class="alert-container">
        @if (TempData.ContainsKey(Constants.Message))
        {
            <div id="alert-message" class="alert alert-@((bool)TempData[Constants.ErrorOccurred] ? "danger" : "success")">
                @TempData[Constants.Message]
            </div>
        }
    </div>

    <form method="get" action="@Url.Action("Search", "Mjesto")">
        <label>Pretraži po imenu mjesta:</label>
        <input type="text" name="naziv" style="border-radius: 5px; padding: 5px; border: 1px solid #ccc; outline: none;" />
        <button class ="btn btn-sm btn-success" type="submit">Pretraži</button>
    </form>


    <div class="grid-container">

        @foreach (var mjesto in Model.mjesta)
        {
            <div class="grid-item">
                <h3>@mjesto.naziv</h3>
                <p><strong>Poštanski broj: </strong> @mjesto.postanskibroj</p>
                <td class="btn-group">
                    <div class="btn-group">
                        <a asp-action="Edit"
                           asp-route-idMjesta="@mjesto.idMjesto"
                           class="btn btn-sm btn-success" title="Ažuriraj"><i class="fas fa-edit"></i>Ažuriraj</a>
                        &nbsp;&nbsp;&nbsp;
                        <form asp-action="Delete" method="post" asp-route-idMjesta="@mjesto.idMjesto">
                            <input type="hidden" name="idMjesto" value="@mjesto.idMjesto" />
                            <button type="submit" class="btn btn-sm btn-danger delete" title="Obriši" onclick="return confirmDelete()"><i class="fas fa-trash-alt"></i>Obriši</button>
                        </form>
                    </div>

                    <script>
                        function confirmDelete() {
                            return confirm('Jeste li sigurni da želite obrisati?');
                        }
                    </script>
                </td>

           

            </div>
        }
    </div>

    <a asp-action="Create" class="btn btn-sm btn-success">Dodaj mjesto</a>

    <script>
        var alertMessage = document.getElementById('alert-message');
        if (alertMessage) {
            setTimeout(function () {
                alertMessage.classList.add('fade-out');
            }, 3000); 
        }
    </script>

    @*<a asp-action="Index" class="btn btn-sm btn-success">Makni filter pretraživanja</a>*@

    <div style="text-align: center;">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Google_Maps_pin.svg/1200px-Google_Maps_pin.svg.png" width="120" height="200" />
    </div>
</body>

Summer/Informacijski sustavi/WebApp/Views/Mjesto/Search.cshtml
@model WebApp.ViewModels.MjestaViewModel
@{
    ViewData["Title"] = "Rezultati pretraživanja";
}
@*<style>
    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }

    img {
        border-radius: 10px;
    }

    div {
        margin-bottom: 10px;
    }

    a {
        color: green;
        text-decoration: none;
    }

    .alert-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 9999; /* Postavite z-index na veliku vrijednost kako bi se poruka prikazala iznad ostalog sadržaja */
    }

    /* Definirajte klasu za fade-out animaciju */
    .fade-out {
        animation: fadeOut ease 2s;
        animation-fill-mode: forwards; /* Drži stilove nakon animacije */
    }

    @@keyframes fadeOut {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0;
        }
    }
</style>
<body>

    <h1>Mjesta</h1>

    <a asp-action="Create">Dodaj novo mjesto</a>


    <div class="alert-container">
        @if (TempData.ContainsKey(Constants.Message))
        {
            <div id="alert-message" class="alert alert-@((bool)TempData[Constants.ErrorOccurred] ? "danger" : "success")">
                @TempData[Constants.Message]
            </div>
        }
    </div>

    <table class="table table-sm table-stripped table-hover" id="vozila">
        <thead>
            <tr>
                <th>
                    <a>
                        Id mjesta
                    </a>
                </th>

                <th>
                    <a>
                        Naziv mjesta
                    </a>
                </th>
                <th>
                    <a>
                        Poštanski broj mjesta
                    </a>
                </th>




            </tr>
        </thead>
        <tbody>
            @foreach (var mjesto in Model.mjesta)
            {
                <tr>
                    <td>@mjesto.idMjesto</td>
                    <td>@mjesto.naziv</td>
                    <td>@mjesto.postanskibroj</td>
                    <td class="btn-group">
                        <a asp-action="Edit"
                           asp-route-idMjesta="@mjesto.idMjesto"
                           class="btn btn-sm btn-success" title="Ažuriraj"><i class="fas fa-edit"></i>Ažuriraj</a>
                        &nbsp;&nbsp;&nbsp;
                        <form asp-action="Delete" method="post" asp-route-idMjesta="@mjesto.idMjesto">
                            <input type="hidden" name="idMjesto" value="@mjesto.idMjesto" />
                            <button type="submit" class="btn-group btn-sm btn-danger delete" title="Obriši" onclick="return confirmDelete()"><i class="fas fa-trash-alt"></i>Obriši</button>
                        </form>

                        <script>
                            function confirmDelete() {
                                return confirm('Jeste li sigurni da želite obrisati?');
                            }
                        </script>
                    </td>
                </tr>

            }
        </tbody>
    </table>



    <div style="text-align: center;">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Google_Maps_pin.svg/1200px-Google_Maps_pin.svg.png" width="120" height="200" />
    </div>

</body>

<script>
    // Check if the alert message exists
    var alertMessage = document.getElementById('alert-message');
    if (alertMessage) {
        // Set a timeout to add the fade-out class after 3-4 seconds
        setTimeout(function () {
            alertMessage.classList.add('fade-out');
        }, 3000); // 3000 milliseconds = 3 seconds
    }
</script>*@

@{
    ViewData["Title"] = "Mjesta";
}

<style>
    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }

    img {
        border-radius: 10px;
    }

    a {
        color: green;
        text-decoration: none;
    }

    .grid-container {
        display: grid;
        grid-template-columns: repeat(4, 1fr); /* 4 stupca */
        gap: 20px;
        padding: 20px;
    }

    .grid-item {
        background-color: rgba(255, 255, 255, 0.8);
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .alert-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 9999; /* Postavite z-index na veliku vrijednost kako bi se poruka prikazala iznad ostalog sadržaja */
    }

    /* Definirajte klasu za fade-out animaciju */
    .fade-out {
        animation: fadeOut ease 2s;
        animation-fill-mode: forwards; /* Drži stilove nakon animacije */
    }

    @@keyframes fadeOut {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0;
        }
    }

</style>

<body>


    <h1>Mjesta</h1>
    <div class="alert-container">
        @if (TempData.ContainsKey(Constants.Message))
        {
            <div id="alert-message" class="alert alert-@((bool)TempData[Constants.ErrorOccurred] ? "danger" : "success")">
                @TempData[Constants.Message]
            </div>
        }
    </div>

    <form method="get" action="@Url.Action("Search", "Mjesto")">
        <label>Pretraži po imenu mjesta:</label>
        <input type="text" name="naziv" style="border-radius: 5px; padding: 5px; border: 1px solid #ccc; outline: none;" />
        <button class="btn btn-sm btn-success" type="submit">Pretraži</button>
    </form>


    <div class="grid-container">

        @foreach (var mjesto in Model.mjesta)
        {
            <div class="grid-item">
                <h3>@mjesto.naziv</h3>
                <p><strong>Poštanski broj: </strong> @mjesto.postanskibroj</p>
                <td class="btn-group">
                    <div class="btn-group">
                        <a asp-action="Edit"
                           asp-route-idMjesta="@mjesto.idMjesto"
                           class="btn btn-sm btn-success" title="Ažuriraj"><i class="fas fa-edit"></i>Ažuriraj</a>
                        &nbsp;&nbsp;&nbsp;
                        <form asp-action="Delete" method="post" asp-route-idMjesta="@mjesto.idMjesto">
                            <input type="hidden" name="idMjesto" value="@mjesto.idMjesto" />
                            <button type="submit" class="btn btn-sm btn-danger delete" title="Obriši" onclick="return confirmDelete()"><i class="fas fa-trash-alt"></i>Obriši</button>
                        </form>
                    </div>

                    <script>
                        function confirmDelete() {
                            return confirm('Jeste li sigurni da želite obrisati?');
                        }
                    </script>
                </td>



            </div>
        }
    </div>

    @*<a asp-action="Create" class="btn btn-sm btn-success">Dodaj smještaj</a>*@

    <script>
        var alertMessage = document.getElementById('alert-message');
        if (alertMessage) {
            setTimeout(function () {
                alertMessage.classList.add('fade-out');
            }, 3000); 
        }
    </script>

    <a asp-action="Index" class="btn btn-sm btn-success">Makni filter pretraživanja</a>

    <div style="text-align: center;">
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Google_Maps_pin.svg/1200px-Google_Maps_pin.svg.png" width="120" height="200" />
    </div>
</body>