Summer/Informacijski sustavi/WebApp/Models/Smjestaj.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class Smjestaj
{
    public int IdSmjestaj { get; set; }

    public int IdObrok { get; set; }

    public int IdSoba { get; set; }

    public int IdVrstaSmjestaja { get; set; }

    public string Naziv { get; set; }

    public virtual Obrok IdObrokNavigation { get; set; }

    public virtual Soba IdSobaNavigation { get; set; }

    public virtual VrstaSmjestaja IdVrstaSmjestajaNavigation { get; set; }

    public virtual ICollection<Putovanje> Putovanjes { get; set; } = new List<Putovanje>();
}

Summer/Informacijski sustavi/WebApp/ViewModels/SmjestajViewModel.cs
namespace WebApp.ViewModels
{
    public class SmjestajViewModel
    {

        public int idSmjestaj { get; set; }
        public string naziv { get; set; }
        public string vrstaObroka { get; set; }
        public string vrstaSmjestaja { get; set; }
        public string vrstaSobe { get; set; }

    }
}

Summer/Informacijski sustavi/WebApp/Controllers/SmjestajController.cs
using WebApp.Models;
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using WebApp.ViewModels;
using System.Text.Json;
using System.Runtime.CompilerServices;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Azure;
using Microsoft.VisualBasic;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApp.Extensions;


namespace WebApp.Controllers
{

    public class SmjestajController : Controller
    {
        private readonly infsusContext ctx;
        private readonly ILogger<SmjestajController> logger;

        public SmjestajController(infsusContext ctx, ILogger<SmjestajController> logger)
        {
            this.ctx = ctx;
            this.logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var query = ctx.Smjestaj.AsNoTracking();
            var smjestaj = query.Select(o => new SmjestajViewModel
            {
                idSmjestaj = o.IdSmjestaj,
                naziv = o.Naziv,
                vrstaObroka = o.IdObrokNavigation.VrstaObroka,
                vrstaSmjestaja = o.IdVrstaSmjestajaNavigation.VrstaSmjestaja1,
                vrstaSobe = o.IdSobaNavigation.VrstaSobe
            });

            var model = new SmjestajiViewModel
            {
                smjestaji = smjestaj,
            };

            return View(model);

        }

        public async Task<IActionResult> Search(string? naziv)
        {
            Console.WriteLine("aha");

            var query = ctx.Smjestaj.AsNoTracking();

            if (naziv != null)
            {
                Console.WriteLine("usao sam u ovo");
                query = ctx.Smjestaj.Where(p => p.Naziv.Equals(naziv));

                bool postoji = await ctx.Smjestaj.AnyAsync(m => m.Naziv == naziv);

                if (!postoji)
                {
                    Console.WriteLine("nemam takav");
                    TempData[Constants.Message] = $"Ne postoji smještaj s tim imenom!!";
                    TempData[Constants.ErrorOccurred] = false;
                    return RedirectToAction(nameof(Index));
                }

                var smjestaj = query.Select(o => new SmjestajViewModel
                {
                    idSmjestaj = o.IdSmjestaj,
                    naziv = o.Naziv,
                    vrstaObroka = o.IdObrokNavigation.VrstaObroka,
                    vrstaSmjestaja = o.IdVrstaSmjestajaNavigation.VrstaSmjestaja1,
                    vrstaSobe = o.IdSobaNavigation.VrstaSobe
                });

                var model = new SmjestajiViewModel
                {
                    smjestaji = smjestaj,
                };

                return View(model);
            }
            else
            {
                Console.WriteLine("nemam takav");
                TempData[Constants.Message] = $"Polje je prazno!!";
                TempData[Constants.ErrorOccurred] = false;
                return RedirectToAction(nameof(Index));
            }




        }


        //stvaranje nove vrste-GET
        [HttpGet]
        public IActionResult Create()
        {
            var obroci = ctx.Obrok.ToList();
            ViewBag.Obroci = new SelectList(obroci, "IdObroka", "VrstaObroka");
            var vrstaSmjestaja1 = ctx.VrstaSmjestaja.ToList();
            ViewBag.VrstaSmjestaja = new SelectList(vrstaSmjestaja1, "IdVrstaSmjestaja", "VrstaSmjestaja1");
            var sobe = ctx.Soba.ToList();
            ViewBag.Sobe = new SelectList(sobe, "IdSobe", "VrstaSobe");
            return View();
        }

        //stvaranje nove vrste-POST
        [HttpPost]
        [ValidateAntiForgeryToken]  
        public IActionResult Create(Smjestaj smjestaj)
        {
            if (ModelState.IsValid)
            {        
                try
                {

                    var postojeciSmjestaj = ctx.Smjestaj.AsNoTracking().FirstOrDefault(m => m.Naziv.Equals(smjestaj.Naziv));
                    if (postojeciSmjestaj != null)
                    {
                        Console.WriteLine("isti naziv");
                        ModelState.AddModelError("Naziv", "Naziv već postoji u bazi podataka.");

                        ViewData["Obroci"] = new SelectList(ctx.Obrok, "IdObroka", "VrstaObroka", smjestaj.IdObrok);
                        ViewData["Sobe"] = new SelectList(ctx.Soba, "IdSobe", "VrstaSobe", smjestaj.IdSoba);
                        ViewData["VrstaSmjestaja"] = new SelectList(ctx.VrstaSmjestaja, "IdVrstaSmjestaja", "VrstaSmjestaja1", smjestaj.IdVrstaSmjestaja);
                        return View(smjestaj);

                    }

                    ctx.Add(smjestaj);
                    ctx.SaveChanges();
                    logger.LogInformation(new EventId(1000), $"Smještaj naziva {smjestaj.Naziv} dodan!");

                    TempData[Constants.Message] = $"Smještaj naziva {smjestaj.Naziv} dodan!";
                    TempData[Constants.ErrorOccurred] = false;
                    Console.WriteLine("Dodana!");
                    return RedirectToAction(nameof(Index));

                }

                catch (Exception exc)
                {
                    Console.WriteLine("Pogreška se dogodila!");
                    logger.LogError("Pogreška prilikom kreiranja smještaja");
                    TempData[Constants.Message] = $"Morate ispuniti sva polja!";
                    TempData[Constants.ErrorOccurred] = false;
                    ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
                    var obroci = ctx.Obrok.ToList();
                    ViewBag.Obroci = new SelectList(obroci, "IdObroka", "VrstaObroka");
                    var vrstaSmjestaja1 = ctx.VrstaSmjestaja.ToList();
                    ViewBag.VrstaSmjestaja = new SelectList(vrstaSmjestaja1, "IdVrstaSmjestaja", "VrstaSmjestaja1");
                    var sobe = ctx.Soba.ToList();
                    ViewBag.Sobe = new SelectList(sobe, "IdSobe", "VrstaSobe");
                    return View();
                }
            }
            else
            {
                var obroci = ctx.Obrok.ToList();
                ViewBag.Obroci = new SelectList(obroci, "IdObroka", "VrstaObroka");
                var vrstaSmjestaja1 = ctx.VrstaSmjestaja.ToList();
                ViewBag.VrstaSmjestaja = new SelectList(vrstaSmjestaja1, "IdVrstaSmjestaja", "VrstaSmjestaja1");
                var sobe = ctx.Soba.ToList();
                ViewBag.Sobe = new SelectList(sobe, "IdSobe", "VrstaSobe");
                return View(smjestaj);
            }
        }

        public IActionResult Delete(int idSmjestaja)
        {
            var brisanje = ctx.Smjestaj.AsNoTracking()
                           .Where(smjestaj => smjestaj.IdSmjestaj == idSmjestaja).SingleOrDefault();
            if (brisanje != null)
            {
                try
                {
                    string naziv = brisanje.Naziv;
                    ctx.Remove(brisanje);
                    ctx.SaveChanges();
                    logger.LogInformation($"Smještaj {naziv} uspješno obrisan");
                    TempData[Constants.Message] = $"Smještaj {naziv} uspješno obrisan";
                    TempData[Constants.ErrorOccurred] = false;
                }
                catch (Exception exc)
                {
                    TempData[Constants.Message] = "Greška prilikom brisanja!";
                    TempData[Constants.ErrorOccurred] = true;
                    logger.LogError("Greška prilikom brisanja!");
                }
            }
            else
            {
                logger.LogWarning("Ne postoji smještaj s ID-jem {0}", idSmjestaja);
                TempData[Constants.Message] = "Ne postoji smještaj s ID-jem " + idSmjestaja;
                TempData[Constants.ErrorOccurred] = true;
            }
            return RedirectToAction(nameof(Index));
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var smjestaj = await ctx.Smjestaj.FindAsync(id);
            if (smjestaj == null)
            {
                return NotFound();
            }

            Console.WriteLine("usao sam");
            ViewData["IdObrok"] = new SelectList(ctx.Obrok, "IdObroka", "VrstaObroka", smjestaj.IdObrok);
            ViewData["IdSoba"] = new SelectList(ctx.Soba, "IdSobe", "VrstaSobe", smjestaj.IdSoba);
            ViewData["IdVrstaSmjestaja"] = new SelectList(ctx.VrstaSmjestaja, "IdVrstaSmjestaja", "VrstaSmjestaja1", smjestaj.IdVrstaSmjestaja);
          

            return View(smjestaj);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdSmjestaj", "IdObrok,IdSoba,IdVrstaSmjestaja,Naziv")] Smjestaj smjestaj)
        {
            if (id != smjestaj.IdSmjestaj)
            {
                return RedirectToAction(nameof(Edit));
            }

            if (ModelState.IsValid)
            {

                bool nazivExists = await ctx.Smjestaj
                .AnyAsync(s => s.Naziv == smjestaj.Naziv && s.IdSmjestaj != smjestaj.IdSmjestaj);

                if (nazivExists)
                {
                    ModelState.AddModelError("Naziv", "Naziv već postoji u bazi podataka.");
                    ViewData["IdObrok"] = new SelectList(ctx.Obrok, "IdObroka", "VrstaObroka", smjestaj.IdObrok);
                    ViewData["IdSoba"] = new SelectList(ctx.Soba, "IdSobe", "VrstaSobe", smjestaj.IdSoba);
                    ViewData["IdVrstaSmjestaja"] = new SelectList(ctx.VrstaSmjestaja, "IdVrstaSmjestaja", "VrstaSmjestaja1", smjestaj.IdVrstaSmjestaja);
                    return View(smjestaj);
                }
                try
                {
                    ctx.Update(smjestaj);

Summer/Informacijski sustavi/WebApp/Views/Smjestaj/Create.cshtml
@model WebApp.Models.Smjestaj
<style>
    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }

    img {
        border-radius: 10px;
    }

    div {
        margin-bottom: 10px;
    }

    a {
        color: green;
        text-decoration: none;
    }

    .alert-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 9999; 
    }


    .fade-out {
        animation: fadeOut ease 2s;
        animation-fill-mode: forwards; 
    }

    @@keyframes fadeOut {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0;
        }
    }
</style>
<body>
    <h3>Unos novog smještaja</h3>

    <form asp-action="Create" method="post">

        <div class="form-group">

            Naziv smještaja:
            <input asp-for="Naziv" class="form-control" />
            <div><span asp-validation-for="Naziv" class="text-danger"></span></div>

            <label for="vrstasmjestaj">Vrsta smještaja:</label>
            <select id="vrstasmjestaj" name="idVrstaSmjestaja" asp-items="ViewBag.VrstaSmjestaja" class="form-control">
                <option value="">Odaberite</option>
            </select>

            <label for="soba">Vrsta sobe:</label>
            <select id="soba" name="idSoba" asp-items="ViewBag.Sobe" class="form-control">
                <option value="">Odaberite</option>
            </select>

            <label for="obrok">Vrsta obroka:</label>
            <select id="obrok" name="idObrok" asp-items="ViewBag.Obroci" class="form-control">
                <option value="">Odaberite</option>
            </select>

       
        </div>


        <div class="alert-container">
            @if (TempData.ContainsKey(Constants.Message))
            {
                <div id="alert-message" class="alert alert-@((bool)TempData[Constants.ErrorOccurred] ? "danger" : "success")">
                    @TempData[Constants.Message]
                </div>
            }
        </div>

        <div class="text-center">
            <button class="btn btn-primary" type="submit">Dodaj</button>
            <a asp-action="Index" class="btn btn-secondary">Odustani</a>
        </div>


    </form>


    <script>
        var alertMessage = document.getElementById('alert-message');
        if (alertMessage) {
            setTimeout(function () {
                alertMessage.classList.add('fade-out');
            }, 3000);
        }
    </script>

</body>
@section scripts {
    <partial name="IncludeValidation" />
}

Summer/Informacijski sustavi/WebApp/Views/Smjestaj/Edit.cshtml
@model WebApp.Models.Smjestaj

@{
    ViewData["Title"] = "Uredi smještaj";
}
<style>
    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }

    img {
        border-radius: 10px;
    }

    div {
        margin-bottom: 10px;
    }

    a {
        color: green;
        text-decoration: none;
    }

    .alert-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 9999; 
    }


    .fade-out {
        animation: fadeOut ease 2s;
        animation-fill-mode: forwards; 
    }

    @@keyframes fadeOut {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0;
        }
    }
</style>
<h2>Uredi smještaj</h2>

<h4>Smještaj</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
     
            <div class="form-group">
                <input type="hidden" asp-for="IdSmjestaj" />
                <label asp-for="Naziv" class="control-label">Naziv:</label>
                <input asp-for="Naziv" class="form-control" />
                <div><span asp-validation-for="Naziv" class="text-danger"></span></div>
            </div>

            <div class="form-group">
                <label asp-for="IdVrstaSmjestaja" class="control-label">Vrsta smještaja</label>
                <select asp-for="IdVrstaSmjestaja" class="form-control" asp-items="ViewBag.IdVrstaSmjestaja"></select>
            </div>

            <div class="form-group">
                <label asp-for="IdSoba" class="control-label">Vrsta sobe:</label>
                <select asp-for="IdSoba" class="form-control" asp-items="ViewBag.IdSoba"></select>
            </div>

            <div class="form-group">
                <label asp-for="IdObrok" class="control-label">Obroci:</label>
                <select asp-for="IdObrok" class="form-control" asp-items="ViewBag.IdObrok"></select>
            </div>
            
            

            
      
            <br />
            <div class="form-group">
                <form asp-action="Edit" asp-route-id="@Model.IdSmjestaj" method="post">
                    <input type="submit" value="Spremi promjene" class="btn btn-primary" />
                </form>
                <a asp-action="Index" class="btn btn-secondary"> Odustani </a>
   

            </div>


            <div class="alert-container">
                @if (TempData.ContainsKey(Constants.Message))
                {
                    <div id="alert-message" class="alert alert-@((bool)TempData[Constants.ErrorOccurred] ? "danger" : "success")">
                        @TempData[Constants.Message]
                    </div>
                }
            </div>
        </form>
    </div>
</div>
<br />

<script>
    var alertMessage = document.getElementById('alert-message');
    if (alertMessage) {
        setTimeout(function () {
            alertMessage.classList.add('fade-out');
        }, 3000);
    }
</script>

Summer/Informacijski sustavi/WebApp/Views/Smjestaj/Index.cshtml
@model WebApp.ViewModels.SmjestajiViewModel
@{
    ViewData["Title"] = "Smjestaji";
}

<style>
    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }

    img {
        border-radius: 10px;
    }

    a {
        color: green;
        text-decoration: none;
    }

    .grid-container {
        display: grid;
        grid-template-columns: repeat(4, 1fr); /* 4 stupca */
        gap: 20px;
        padding: 20px;
    }

    .grid-item {
        background-color: rgba(255, 255, 255, 0.8);
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .alert-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 9999; 
    }

    .fade-out {
        animation: fadeOut ease 2s;
        animation-fill-mode: forwards; 
    }

    @@keyframes fadeOut {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0;
        }
    }

   

   

  
</style>

<body>

    <h1>Smještaji</h1>
    <div class="alert-container">
        @if (TempData.ContainsKey(Constants.Message))
        {
            <div id="alert-message" class="alert alert-@((bool)TempData[Constants.ErrorOccurred] ? "danger" : "success")">
                @TempData[Constants.Message]
            </div>
        }
    </div>

    <form method="get" action="@Url.Action("Search", "Smjestaj")">
        <label>Pretraži po imenu smještaja:</label>
        <input type="text" name="naziv" style="border-radius: 5px; padding: 5px; border: 1px solid #ccc; outline: none;" />
        <button class="btn btn-sm btn-success" type="submit">Pretraži</button>
    </form>
   

    <div class="grid-container">

        @foreach(var smjestaj in Model.smjestaji)
        {
            <div class="grid-item">
                <h3>@smjestaj.naziv</h3>
                <p><strong>Vrsta smještaja: </strong> @smjestaj.vrstaSmjestaja</p>
                <p><strong>Vrsta sobe: </strong> @smjestaj.vrstaSobe</p>
                <p><strong>Obroci: </strong> @smjestaj.vrstaObroka</p>
                <td class="btn-group">
                    <div class="btn-group">
                        <a asp-action="Edit"
                           asp-route-id="@smjestaj.idSmjestaj"
                           class="btn btn-sm btn-success" title="Ažuriraj"><i class="fas fa-edit"></i>Ažuriraj</a>
                        &nbsp;&nbsp;&nbsp;
                        <form asp-action="Delete" method="post" asp-route-idSmjestaja="@smjestaj.idSmjestaj">
                            <input type="hidden" name="idSmjestaj" value="@smjestaj.idSmjestaj" />
                            <button type="submit" class="btn btn-sm btn-danger delete" title="Obriši" onclick="return confirmDelete()"><i class="fas fa-trash-alt"></i>Obriši</button>
                        </form>
                    </div>

                    <script>
                        function confirmDelete() {
                            return confirm('Jeste li sigurni da želite obrisati?');
                        }
                    </script>
                </td>

            </div>
        }
    </div>

    <a asp-action="Create" class="btn btn-sm btn-success">Dodaj smještaj</a>

    <script>
        var alertMessage = document.getElementById('alert-message');
        if (alertMessage) {
            setTimeout(function () {
                alertMessage.classList.add('fade-out');
            }, 3000);
        }
    </script>

    @*<a asp-action="Index" class="btn btn-sm btn-success">Makni filter pretraživanja</a>*@


    <div style="text-align: center;">
        <img src="https://www.nichepursuits.com/wp-content/uploads/2023/06/hotel-nam.png" width="300" height="200" />
    </div>
</body>

Summer/Informacijski sustavi/WebApp/Views/Smjestaj/Search.cshtml
@model WebApp.ViewModels.SmjestajiViewModel
@{
    ViewData["Title"] = "Pretraživanje smještaja";
}



<style>
    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }

    img {
        border-radius: 10px;
    }

    a {
        color: green;
        text-decoration: none;
    }

    .grid-container {
        display: grid;
        grid-template-columns: repeat(4, 1fr); /* 4 stupca */
        gap: 20px;
        padding: 20px;
    }

    .grid-item {
        background-color: rgba(255, 255, 255, 0.8);
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    .alert-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 9999; 
    }
    .fade-out {
        animation: fadeOut ease 2s;
        animation-fill-mode: forwards; 
    }

    @@keyframes fadeOut {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0;
        }
    }

</style>

<body>

    <h1>Smještaji</h1>
    <div class="alert-container">
        @if (TempData.ContainsKey(Constants.Message))
        {
            <div id="alert-message" class="alert alert-@((bool)TempData[Constants.ErrorOccurred] ? "danger" : "success")">
                @TempData[Constants.Message]
            </div>
        }
    </div>

    <form method="get" action="@Url.Action("Search", "Smjestaj")">
        <label>Pretraži po imenu smještaja:</label>
        <input type="text" name="naziv" style="border-radius: 5px; padding: 5px; border: 1px solid #ccc; outline: none;" />
        <button class="btn btn-sm btn-success" type="submit">Pretraži</button>
    </form>


    <div class="grid-container">

        @foreach (var smjestaj in Model.smjestaji)
        {
            <div class="grid-item">
                <h3>@smjestaj.naziv</h3>
                <p><strong>Vrsta smještaja: </strong> @smjestaj.vrstaSmjestaja</p>
                <p><strong>Vrsta sobe: </strong> @smjestaj.vrstaSobe</p>
                <p><strong>Obroci: </strong> @smjestaj.vrstaObroka</p>
                <td class="btn-group">
                    <div class="btn-group">
                        <a asp-action="Edit"
                           asp-route-id="@smjestaj.idSmjestaj"
                           class="btn btn-sm btn-success" title="Ažuriraj"><i class="fas fa-edit"></i>Ažuriraj</a>
                        &nbsp;&nbsp;&nbsp;
                        <form asp-action="Delete" method="post" asp-route-idSmjestaja="@smjestaj.idSmjestaj">
                            <input type="hidden" name="idSmjestaj" value="@smjestaj.idSmjestaj" />
                            <button type="submit" class="btn btn-sm btn-danger delete" title="Obriši" onclick="return confirmDelete()"><i class="fas fa-trash-alt"></i>Obriši</button>
                        </form>
                    </div>

                    <script>
                        function confirmDelete() {
                            return confirm('Jeste li sigurni da želite obrisati?');
                        }
                    </script>
                </td>

            </div>
        }
    </div>

    @*<a asp-action="Create" class="btn btn-sm btn-success">Dodaj smještaj</a>*@

    <script>
        var alertMessage = document.getElementById('alert-message');
        if (alertMessage) {
            setTimeout(function () {
                alertMessage.classList.add('fade-out');
            }, 3000); 
        }
    </script>

    <a asp-action="Index" class="btn btn-sm btn-success">Makni filter pretraživanja</a>


    <div style="text-align: center;">
        <img src="https://www.nichepursuits.com/wp-content/uploads/2023/06/hotel-nam.png" width="300" height="200" />
    </div>
</body>