Summer/Informacijski sustavi/WebApp/Models/Putovanje.cs
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class Putovanje
{
    public int IdPutovanja { get; set; }

    public int IdMjesto { get; set; }

    public int IdSmjestaj { get; set; }

    public int IdVrstaPutovanja { get; set; }

    public int IdVozilo { get; set; }

    public string Opis { get; set; }

    public string ImeprezimeVoditelj { get; set; }

    public int Cijena { get; set; }

    public DateTime DatumPolaska { get; set; }

    public DateTime DatumPovratka { get; set; }

    public byte[] Slika { get; set; }

    public string Rate { get; set; }

    public virtual Mjesto IdMjestoNavigation { get; set; }

    public virtual Smjestaj IdSmjestajNavigation { get; set; }

    public virtual Vozilo IdVoziloNavigation { get; set; }

    public virtual VrstaPutovanja IdVrstaPutovanjaNavigation { get; set; }

    public virtual ICollection<Rezervacija> Rezervacijas { get; set; } = new List<Rezervacija>();
}

Summer/Informacijski sustavi/WebApp/ViewModels/PutovanjeViewModel.cs
namespace WebApp.ViewModels
{
    public class PutovanjeViewModel
    {
        public int IdPutovanja { get; set; }
        public string Opis { get; set; }
        public int Cijena { get; set; }

        public DateTime DatumPolaska { get; set; }

        public DateTime DatumPovratka { get; set; }
    }
}

Summer/Informacijski sustavi/WebApp/Controllers/PutovanjeController.cs
using WebApp;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using System.Reflection.Metadata;
using WebApp.Models;
using WebApp.ViewModels;


namespace WebApp.Controllers
{
    public class PutovanjeController : Controller
    {

        private readonly infsusContext ctx;
        private readonly ILogger<PutovanjeController> logger;


        public PutovanjeController(infsusContext ctx, ILogger<PutovanjeController> logger)
        {
            this.ctx=ctx;
            this.logger=logger;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewData["IdMjesto"] = new SelectList(ctx.Mjesto, "IdMjesto", "Naziv");
            ViewData["IdSmjestaj"] = new SelectList(ctx.Smjestaj, "IdSmjestaj", "Naziv");
            ViewData["IdVozilo"] = new SelectList(ctx.Vozilo, "IdVozila", "VrstaVozila");
            ViewData["IdVrstaPutovanja"] = new SelectList(ctx.VrstaPutovanja, "IdVrste", "NazivVrstePut");
            ViewData["IdVrstaSobe"] = new SelectList(ctx.Soba, "IdSobe", "VrstaSobe");

            var rateOptions = new List<SelectListItem>
            {
                new SelectListItem {Value = "da", Text = "da"},
                new SelectListItem {Value = "ne", Text = "ne"}
            };

            ViewData["Rate"] = new SelectList(rateOptions, "Value", "Text");
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdMjesto,IdSmjestaj,IdVrstaPutovanja,IdVozilo,Opis,ImeprezimeVoditelj,Cijena,DatumPolaska,DatumPovratka,Rate")] Putovanje putovanje)
        {
            if (ModelState.IsValid)
            {
                ctx.Add(putovanje);
                await ctx.SaveChangesAsync();
                TempData[Constants.Message] = "Uspješno dodano putovanje";
                TempData[Constants.ErrorOccurred] = false;
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdMjesto"] = new SelectList(ctx.Mjesto, "IdMjesto", "Naziv");
            ViewData["IdSmjestaj"] = new SelectList(ctx.Smjestaj, "IdSmjestaj", "Naziv");
            ViewData["IdVozilo"] = new SelectList(ctx.Vozilo, "IdVozila", "VrstaVozila");
            ViewData["IdVrstaPutovanja"] = new SelectList(ctx.VrstaPutovanja, "IdVrste", "NazivVrstePut");

            var rateOptions = new List<SelectListItem>
            {
                new SelectListItem {Value = "da", Text = "da"},
                new SelectListItem {Value = "ne", Text = "ne"}
            };

            ViewData["Rate"] = new SelectList(rateOptions, "Value", "Text");
            TempData[Constants.Message] = "Neuspješno dodano putovanje, dogodila se greška!";
            TempData[Constants.ErrorOccurred] = true;

            return View(putovanje);
        }

    
        public async Task<IActionResult> Delete(int id)
        {
            var putovanje = await ctx.Putovanje.FindAsync(id);
            if (putovanje == null)
            {
                return NotFound();
            }

            try
            {
                ctx.Putovanje.Remove(putovanje);
                await ctx.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // Log the exception (optional)
                // logger.LogError(ex, "An error occurred while deleting the record.");

                // Pass the error message to the Index action
                TempData[Constants.Message] = "Došlo je do greške prilikom brisanja zapisa.";
                TempData[Constants.ErrorOccurred] = true;
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var putovanje = await ctx.Putovanje.FindAsync(id);
            if (putovanje == null)
            {
                return NotFound();
            }


            ViewData["IdMjesto"] = new SelectList(ctx.Mjesto, "IdMjesto", "Naziv", putovanje.IdMjesto);
            ViewData["IdSmjestaj"] = new SelectList(ctx.Smjestaj, "IdSmjestaj", "Naziv", putovanje.IdSmjestaj);
            ViewData["IdVozilo"] = new SelectList(ctx.Vozilo, "IdVozila", "VrstaVozila", putovanje.IdVozilo);
            ViewData["IdVrstaPutovanja"] = new SelectList(ctx.VrstaPutovanja, "IdVrste", "NazivVrstePut", putovanje.IdVrstaPutovanja);
            var rateOptions = new List<SelectListItem>
            {
                new SelectListItem {Value = "da", Text = "da"},
                new SelectListItem {Value = "ne", Text = "ne"}
            };

            ViewData["Rate"] = new SelectList(rateOptions, "Value", "Text", putovanje.Rate);

            return View(putovanje);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPutovanja","IdMjesto,IdSmjestaj,IdVrstaPutovanja,IdVozilo,Opis,ImeprezimeVoditelj,Cijena,DatumPolaska,DatumPovratka,Rate")] Putovanje putovanje)
        {
            if (id != putovanje.IdPutovanja)
            {
                return RedirectToAction(nameof(Edit));
            }

            if (ModelState.IsValid)
            {
                try
                {
                    ctx.Update(putovanje);
                    await ctx.SaveChangesAsync();
                }
                catch(Exception)
                {
                    if (!PutovanjeExists(putovanje.IdPutovanja))
                    {
                        TempData["ErrorMessage"] = "Došlo je do greške prilikom uređivanja putovanja.";
                        return RedirectToAction(nameof(Index));
                    } else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }
            return View(putovanje);
        }

        private bool PutovanjeExists(int id)
        {
            return ctx.Putovanje.Any(p => p.IdPutovanja == id);
        }
        public async Task<IActionResult> Index(DateTime? datumPolaska, DateTime? datumPovratka, int page = 1, int pageSize = 4)
        {
            var query = ctx.Putovanje.AsNoTracking();

            if (datumPolaska != null)
            {
                query = query.Where(p => p.DatumPolaska >= datumPolaska);
            }

            if (datumPovratka != null)
            {
                query = query.Where(p => p.DatumPovratka <= datumPovratka);
            }



  
            var totalCount = await query.CountAsync();
            var totalPages = (int)Math.Ceiling(totalCount / (double)pageSize);
            var putovanjaStranica = query.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            var putovanje = putovanjaStranica.Select(o => new PutovanjeViewModel
            {
                IdPutovanja = o.IdPutovanja,
                Opis = o.Opis,
                Cijena = o.Cijena,
                DatumPolaska = o.DatumPolaska,
                DatumPovratka = o.DatumPovratka

            });

            var model = new PutovanjaViewModel
            {
                putovanja = putovanje,
                CurrentPageNumber = page,
                TotalPages = totalPages,
                PageSize = pageSize,
                TotalCount = totalCount,
                PageNumber = page

            };

            return View(model);

            


            
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Putovanje putovanje =  ctx.Putovanje
                                  .Include("IdMjestoNavigation")
                                  .Include("IdSmjestajNavigation")
                                  .Include("IdVoziloNavigation")
                                  .Include("IdVrstaPutovanjaNavigation")
                                  .Include(p => p.IdSmjestajNavigation)
                                  .ThenInclude(s => s.IdSobaNavigation)
                                  .Include(p => p.IdSmjestajNavigation)
                                  .ThenInclude(s => s.IdObrokNavigation)
                                  .Include(p => p.Rezervacijas)
                                  .ThenInclude(r => r.IdKorisnikNavigation)
                                  .Include(p => p.IdSmjestajNavigation)
                                  .ThenInclude(s => s.IdVrstaSmjestajaNavigation)
                                   .FirstOrDefault(p => p.IdPutovanja == id);

            if (putovanje == null)
            {
                return NotFound();
            }
            return View(putovanje);
        }


        
    }
}

Summer/Informacijski sustavi/WebApp/Views/Putovanje/Create.cshtml
@using WebApp
@model WebApp.Models.Putovanje


@{
    ViewData["Title"] = "Kreiraj novo putovanje";
}

<style>
    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }

    .alert-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 9999;
    }

    .fade-out {
        animation: fadeOut ease 2s;
        animation-fill-mode: forwards;
    }

    @@keyframes fadeOut {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0;
        }
    }


</style>
<h2>Kreiraj novo putovanje</h2>
<div class="alert-container">
    @if (TempData.ContainsKey(Constants.Message))
    {
        <div id="alert-message" class="alert alert-@((bool)TempData[Constants.ErrorOccurred] ? "danger" : "success")">
            @TempData[Constants.Message]
        </div>
    }
</div>
<h4>Putovanje</h4>
<hr />
<div class="alert-container">
    @if (TempData.ContainsKey(Constants.Message))
    {
        <div class="alert alert-@((bool)TempData[Constants.ErrorOccurred] ? "danger" : "success")">
            @TempData[Constants.Message]
        </div>
    }
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label class="control-label">Mjesto</label>
                <select asp-for="IdMjesto" class="form-control" asp-items="ViewBag.IdMjesto">
                </select>
            </div>
            <div class="form-group">
                <label class="control-label">Smještaj</label>
                <select asp-for="IdSmjestaj" class="form-control" asp-items="ViewBag.IdSmjestaj"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Vozilo</label>
                <select asp-for="IdVozilo" class="form-control" asp-items="ViewBag.IdVozilo"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Vrsta putovanja</label>
                <select asp-for="IdVrstaPutovanja" class="form-control" asp-items="ViewBag.IdVrstaPutovanja"></select>
            </div>
            <div class="form-group">
                <label class="control-label">Opis</label>
                <input asp-for="Opis" class="form-control" />
                <div><span asp-validation-for="Opis" class="text-danger"></span></div>
            </div>
            <div class="form-group">
                <label class="control-label">Ime i prezime voditelja</label>
                <input asp-for="ImeprezimeVoditelj" class="form-control" />
                <div><span asp-validation-for="ImeprezimeVoditelj" class="text-danger"></span></div>
            </div>
            <div class="form-group">
                <label class="control-label">Cijena</label>
                <input asp-for="Cijena" class="form-control" />
                <div><span asp-validation-for="Cijena" class="text-danger"></span></div>
            </div>
            <div class="form-group">
                <label class="control-label">Datum polaska</label>
                <input asp-for="DatumPolaska" class="form-control" type="date" />
                <div><span asp-validation-for="DatumPolaska" class="text-danger"></span></div>
            </div>
            <div class="form-group">
                <label class="control-label">Datum povratka</label>
                <input asp-for="DatumPovratka" class="form-control" type="date" />
                <div><span asp-validation-for="DatumPovratka" class="text-danger"></span></div>
            </div>
            <div class="form-group">
                <label class="control-label">Rate (da/ne)</label>
                <select asp-for="Rate" class="form-control" asp-items="ViewBag.Rate"></select>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Kreiraj" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Odustani</a>
            </div>

        </form>
    </div>
</div>
<br />

<script>
    var alertMessage = document.getElementById('alert-message');
    if (alertMessage) {
        setTimeout(function () {
            alertMessage.classList.add('fade-out');
        }, 3000);
    }
</script>

@section scripts {
    <partial name="IncludeValidation" />
}

Summer/Informacijski sustavi/WebApp/Views/Putovanje/Details.cshtml
@model WebApp.Models.Putovanje

@{
    ViewBag.Title = "Detalji putovanja";
}


<style>

    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }
    .container {
        display: flex;
        width: 100%;
    }

    .card {
        background: white;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
        margin: 10px;
        flex: 1;
        min-width: 300px;
    }

    .reservations-table {
        background: white;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        padding: 20px;
        margin: 10px;
        flex: 2;
        min-width: 600px;
    }

        .card h4, .reservations-table h4 {
            margin-top: 0;
        }

    .card dt {
        font-weight: bold;
    }

    .card dd {
        margin-bottom: 10px;
    }

    .reservations-table {
        overflow-x: hidden;
        width: 100%;
    }

        .reservations-table table {
            width: 100%;
            border-collapse: collapse;
        }

        .reservations-table th,
        .reservations-table td {
            border: 1px solid #ddd;
            padding: 10px;
        }

        .reservations-table th {
            background-color: #f2f2f2;
            text-align: left;
        }

        a {
            margin: 3px;
            text-decoration: none;
        }
</style>
<a asp-action="Index" class="btn btn-secondary">Povratak</a>
<div class="container">
<div class="card">

    <h4>Detalji putovanja</h4>
    <hr />
    <dl class="dl-horizontal">

        

        <dt>Mjesto: </dt>
        <dd>@Model.IdMjestoNavigation.Naziv</dd>

        <dt>Vrsta putovanja</dt>
        <dd>@Model.IdVrstaPutovanjaNavigation.NazivVrstePut</dd>

        <dt>Opis:</dt>
        <dd>@Model.Opis</dd>

        <dt>Naziv smještaja:</dt>
        <dd>@Model.IdSmjestajNavigation.Naziv</dd>

        <dt>Vrsta smještaja:</dt>
        <dd>@Model.IdSmjestajNavigation.IdVrstaSmjestajaNavigation.VrstaSmjestaja1</dd>

        <dt>Vrsta soba:</dt>
        <dd>@Model.IdSmjestajNavigation.IdSobaNavigation.VrstaSobe</dd>

        <dt>Vrsta obroka:</dt>
        <dd>@Model.IdSmjestajNavigation.IdObrokNavigation.VrstaObroka</ dd>

        <dt>Vozilo:</dt>
        <dd>@Model.IdVoziloNavigation.VrstaVozila</dd>

        <dt>Cijena:</dt>
        <dd>@Model.Cijena €</dd>

        <dt>Datum Polaska:</dt>
        <dd>@Model.DatumPolaska.ToString("dd.MM.yyyy")</dd>

        <dt>Datum Povratka:</dt>
        <dd>@Model.DatumPovratka.ToString("dd.MM.yyyy")</dd>

        <dt>Rate:</dt>
        <dd>@Model.Rate</dd>



    </dl>
    </div>

    
 
    <div class="reservations-table">
        <h4>Rezervacije za putovanje</h4>
        <hr />
        <table>
            <thead>
                <tr>
                    <th>Datum rezervacije</th>
                    <th>Ime klijenta</th>
                    <th>Prezime klijenta</th>
                    <th>Email klijenta</th>
                    <th>Potvrđena (0/1)</th>
                    <th>Broj mjesta</th>
                    <th>Opcije</th>

                </tr>
            </thead>

            <tbody>
                @foreach(var rezervacija in Model.Rezervacijas)
                {
                    <tr>
                        <td>@rezervacija.DatumRezervacije.ToString("dd.MM.yyyy")</td>
                        <td>@rezervacija.IdKorisnikNavigation.Ime</td>
                        <td>@rezervacija.IdKorisnikNavigation.Prezime</td>
                        <td>@rezervacija.IdKorisnikNavigation.Email</td>
                        <td>@rezervacija.Potvrdeno</td>
                        <td>@rezervacija.BrojMjesta</td>
                        
                        <td>
                            <a href="@Url.Action("Edit", "Rezervacija", new { id = @rezervacija.IdRezervacija })" class="btn btn-sm btn-success">Ažuriraj</a>
                            <br />
                            <a href="@Url.Action("Delete", "Rezervacija", new { id = @rezervacija.IdRezervacija })" class="btn-group btn-sm btn-danger delete" onclick="return confirm('Jeste li sigurni da želite obrisati ovu rezervaciju?');">Obriši</a>
                        </td>
                        
                    </tr>
                }

            </tbody>


        </table>
        <hr />
            <div class="create-reservation">
                <a href="@Url.Action("Create", "Rezervacija", new { id = @Model.IdPutovanja })" class="btn btn-success">Kreiraj novu rezervaciju</a>
            </div>
    </div>


    
</div>

Summer/Informacijski sustavi/WebApp/Views/Putovanje/Edit.cshtml
@model WebApp.Models.Putovanje

@{
    ViewData["Title"] = "Uredi putovanje";
}

<h2>Uredi putovanje</h2>

<h4>Putovanje</h4>
<hr />

<style>
    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }
</style>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            
            <div class="form-group">
                <input type="hidden" asp-for="IdPutovanja" />
                <label asp-for="IdMjesto" class="control-label">Mjesto</label>
                <select asp-for="IdMjesto" class="form-control" asp-items="ViewBag.IdMjesto"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdSmjestaj" class="control-label">Smještaj</label>
                <select asp-for="IdSmjestaj" class="form-control" asp-items="ViewBag.IdSmjestaj"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdVozilo" class="control-label">Vozilo</label>
                <select asp-for="IdVozilo" class="form-control" asp-items="ViewBag.IdVozilo"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdVrstaPutovanja" class="control-label">Vrsta putovanja</label>
                <select asp-for="IdVrstaPutovanja" class="form-control" asp-items="ViewBag.IdVrstaPutovanja"></select>
            </div>

            <div class="form-group">
                <label asp-for="Opis" class="control-label">Opis</label>
                <input asp-for="Opis" class="form-control" />
                <div><span asp-validation-for="Opis" class="text-danger"></span></div>
            </div>
            <div class="form-group">
                <label asp-for="ImeprezimeVoditelj" class="control-label">Ime i prezime voditelja</label>
                <input asp-for="ImeprezimeVoditelj" class="form-control" />
                <div><span asp-validation-for="ImeprezimeVoditelj" class="text-danger"></span></div>
            </div>
            <div class="form-group">
                <label asp-for="Cijena" class="control-label">Cijena</label>
                <input asp-for="Cijena" class="form-control" />
                <div><span asp-validation-for="Cijena" class="text-danger"></span></div>
            </div>
            <div class="form-group">
                <label asp-for="DatumPolaska" class="control-label">Datum polaska</label>
                <input asp-for="DatumPolaska" class="form-control" type="date" />
                <div><span asp-validation-for="DatumPolaska" class="text-danger"></span></div>
            </div>
            <div class="form-group">
                <label asp-for="DatumPovratka" class="control-label">Datum povratka</label>
                <input asp-for="DatumPovratka" class="form-control" type="date" />
                <div><span asp-validation-for="DatumPovratka" class="text-danger"></span></div>
            </div>
            <div class="form-group">
                <label asp-for="Rate" class="control-label">Rate (da/ne)</label>
                <select asp-for="Rate" class="form-control" asp-items="ViewBag.Rate"></select>
            </div>
            <br />
            <div class="form-group">
                <form asp-action="Edit" asp-route-id="@Model.IdPutovanja" method="post">
                    <input type="submit" value="Spremi promjene" class="btn btn-primary" />
                </form>
                <a asp-action="Index" class="btn btn-secondary">Odustani</a>
                
            </div>
        </form>
    </div>
</div>
<br />

Summer/Informacijski sustavi/WebApp/Views/Putovanje/Index.cshtml
@using WebApp
@model WebApp.ViewModels.PutovanjaViewModel;
@{
    ViewData["Title"] = "Putovanja";
}

<style>
    body {
        background-image: url('https://coolbackgrounds.io/images/backgrounds/index/ranger-4df6c1b6.png');
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center center;
    }

    img {
        border-radius: 10px;
    }

    a {
        color: black;
        text-decoration: none;
    }

    .grid-container {
        display: grid;
        grid-template-columns: repeat(4, 1fr); /* 4 stupca */
        gap: 20px;
        padding: 20px;
    }

    .grid-item {
        background-color: rgba(255, 255, 255, 0.8);
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }



    .action-buttons {
        margin-top: 10px;
    }

    button {
        margin: 3px;
    }

    .alert-container {
        position: fixed;
        bottom: 20px;
        right: 20px;
        z-index: 9999;
    }

    .fade-out {
        animation: fadeOut ease 2s;
        animation-fill-mode: forwards;
    }

    @@keyframes fadeOut {
        0% {
            opacity: 1;
        }

        100% {
            opacity: 0;
        }
    }

</style>

<body>

    <h1>Putovanja</h1>
    <div class="alert-container">
        @if (TempData.ContainsKey(Constants.Message))
        {
            <div id="alert-message" class="alert alert-@((bool)TempData[Constants.ErrorOccurred] ? "danger" : "success")">
                @TempData[Constants.Message]
            </div>
        }
    </div>

    <form method="get" action="@Url.Action("Index", "Putovanje")" id="filterForm">
        <label for="datumPolaska">Datum polaska:</label>
        <input type="date" name="datumPolaska" id="datumPolaska" />
        <label for="datumPovratka">Datum povratka:</label>
        <input type="date" name="datumPovratka" id="datumPovratka" min="" />
        <button class="btn btn-sm btn-success" type="submit">Filtriraj</button>
        <a class="btn btn-sm btn-success" asp-action="Index" asp-router="Putovanje">Poništi filter</a>
    </form>

    <script>
        var datumPolaskaInput = document.getElementById("datumPolaska");
        var datumPovratkaInput = document.getElementById("datumPovratka");

        datumPolaskaInput.addEventListener("change", function () {
            datumPovratkaInput.min = datumPolaskaInput.value;
            if (datumPovratkaInput.value < datumPolaskaInput.value) {
                datumPovratkaInput.value = "";
            }
        });
    </script>


    <div class="grid-container">

        @foreach(var putovanje in Model.putovanja)
        {
            <div class="grid-item">
                <a asp-action="Details" asp-controller="Putovanje" asp-route-id="@putovanje.IdPutovanja">
                <h3>@putovanje.Opis</h3>
                <p><strong>Cijena: </strong> @putovanje.Cijena €</p>
                    <p><strong>Datum polaska: </strong> @putovanje.DatumPolaska.ToString("dd.MM.yyyy")</p>
                    <p><strong>Datum povratka: </strong> @putovanje.DatumPovratka.ToString("dd.MM.yyyy")</p>
                </a>
                <div class="action-buttons">
                    <a class="btn btn-sm btn-success" asp-action="Edit" asp-controller="Putovanje" asp-route-id="@putovanje.IdPutovanja">Uredi</a>
                    <a class="btn-group btn-sm btn-danger delete" asp-action="Delete" asp-controller="Putovanje" asp-route-id="@putovanje.IdPutovanja"
                       onclick="return confirm('Jeste li sigurni da želite obrisati ovo putovanje?');">Izbriši</a>
                </div>
            </div>
        }
    </div>
    <a class="btn btn-sm btn-success" asp-action="Create">Kreiraj Novo Putovanje</a>
    <page url="@Url.Action("Index")" page="Model.PageNumber" page-size="Model.PageSize" total-items="Model.TotalCount"></page>
    
    <div class="pagination">
        @if (Model.TotalPages > 1)
        {
            @if (Model.PageNumber > 1)
            {
                <button class="btn btn-primary" onclick="changePage(@Model.PageNumber - 1)">&lt;</button>
            }

            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                <button class="btn btn-primary" onclick="changePage(@i)" @(i == Model.PageNumber ? "disabled" : "")>@i</button>
            }

            @if (Model.PageNumber < Model.TotalPages)
            {
                <button class="btn btn-primary" onclick="changePage(@Model.PageNumber + 1)">&gt;</button>
            }
        }
    </div>

    <script>
        function changePage(pageNumber) {
            window.location.href = "@Url.Action("Index")?page=" + pageNumber;
        }
    </script>
    <script>
        var alertMessage = document.getElementById('alert-message');
        if (alertMessage) {
            setTimeout(function () {
                alertMessage.classList.add('fade-out');
            }, 3000);
        }
    </script>

</body>